# Generated by Django 5.0.6 on 2024-07-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_navitem_rename_link_autor_nacionalidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="descripcion",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
